name: PPOTTO BFF ECR push and deploy to ECS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 프로젝트 로드
        uses: actions/checkout@v4

      - name: 프로젝트 환경변수 생성
        run: |
          echo ${{ secrets.ENV_PROD }} >> ./environments/.env.production

      - name: AWS 로그인
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: ECR 로그인
        id: ecr-login-info
        uses: aws-actions/amazon-ecr-login@v1

      - name: 이미지 빌드 및 ECR 푸시
        id: build-image-info
        env:
          ECR_REGISTRY: ${{ steps.ecr-login-info.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --build-arg NODE_ENV=production .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
